name: RPG-CORE
version: '${project.version}'
main: rpg.rpgcore.RPGCORE
softdepend:
  - MythicMobs
  - HolographicDisplays
  - WorldGuard
authors: [ MiresPL, ZwariowanyOrzel ]
description: RPG-CORE
    