name: RPG-CORE
version: '${project.version}'
main: rpg.rpgcore.RPGCORE
depend:
  - MythicMobs
authors: [ MiresPL, ZwariowanyOrzel ]
description: RPG-CORE
commands:
  spawn:
  
  teleport:
    aliases: tp
  teleportcoords:
    aliases: tpcoords
  ban:
  
  unban:
  
  kick:
  
  vanish:
    aliases: v
  god:
  
  speed:
  
  fly:
  
  back:
  
  history:
  
  lvl:
  
  gamemode:
    aliases:
      - gm

  heal:
      
  tempban:

  osiagniecia:
    aliases:
      - os

  setdmg:

  akcesoria:
    aliases:
      - akce
  pomoc:
    aliases:
      - help

  sprawdzmojebonusy:
    aliases:
      - smb

  mute:

  unmute:

  tempmute:

  message:
    aliases:
      - msg
      - pw
      - m

  reply:
    aliases:
      - r


  testanimation:

  targ:
    aliases:
      - market
      - ah

  kasa:
    aliases:
      - bal
      - balance
      - money
      - kaska

  wyplac:
    aliases:
      - withdraw

  wystaw:

  sprawdz:

  test:

  magazyn:

  klan:
    aliases:
      - g

  kosz:
    aliases:
      - k

  helpop:
    