name: RPG-CORE
version: '${project.version}'
main: rpg.rpgcore.RPGCORE
authors: [ Caufland, MiresPL ]
description: RPG-CORE
commands:
  spawn:

  teleport:
    aliases: tp
  teleportcoords:
    aliases: tpcoords
  ban:

  unban:

  kick:

  vanish:
